name: telegram_chart_analytics
description: Telegram chart analytic

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  qr_code_scanner: ^1.0.1
  get_it: ^7.2.0
  flutter_svg: ^2.0.1
  theme_tailor_annotation: ^1.0.3
  go_router: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  theme_tailor: ^1.0.8


flutter:

  uses-material-design: true

